- name: Setup static server
  hosts: all
  roles:
    - role: users_common
    - role: system_maintenance
    - role: ohmyzsh
    - role: ssh
      become: true # Пришлось указывать на уровне плейбука, потому что линтер ругается на использование become внутри роли, из-за модуля lineinfile
    - role: nginx
      become: true
    - role: static_delivery
