---
- name: Download static files
  ansible.builtin.get_url:
    url: "{{ item }}"
    dest: "/tmp/images/"
    mode: '0777'
  loop: "{{ static_delivery_url }}"

# - name: Reload nginx
#   ansible.builtin.service:
#     name: nginx
#     state: reloaded
