---
- name: Update apt cache
  ansible.builtin.apt:
    update_cache: true
  become: true

- name: Upgrade all packages
  ansible.builtin.apt:
    upgrade: dist
  become: true

- name: Installation packages
  ansible.builtin.apt:
    name: "{{ item }}"
    state: present
  loop:
    - "{{ system_maintenance_packages }}" # Переменная из vars/main.yml
  become: true
